#!/usr/bin/env bun
// ABOUTME: Bumps the version across all Limn packages, commits the change, tags it, and pushes.
// ABOUTME: Usage: bun run scripts/bump-version.ts [version] -- defaults to patch bump if no version given.

import { readFileSync, writeFileSync, unlinkSync } from "fs";
import { execSync } from "child_process";
import { join, resolve } from "path";
import { tmpdir } from "os";

const ROOT = join(import.meta.dirname, "..");

const VERSION_FILES = [
  "packages/core/package.json",
  "packages/web/package.json",
  "packages/obsidian/package.json",
  "packages/obsidian/manifest.json",
  "manifest.json",
];

const DESKTOP_PROJECT_YML = "packages/desktop/project.yml";

const VERSIONS_JSON = "packages/obsidian/versions.json";

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(ROOT, path), "utf-8"));
}

function writeJson(path: string, data: Record<string, unknown>): void {
  writeFileSync(join(ROOT, path), JSON.stringify(data, null, 2) + "\n");
}

function bumpPatch(version: string): string {
  const parts = version.split(".");
  if (parts.length !== 3) throw new Error(`Invalid version: ${version}`);
  parts[2] = String(Number(parts[2]) + 1);
  return parts.join(".");
}

function run(cmd: string): void {
  console.log(`$ ${cmd}`);
  execSync(cmd, { cwd: ROOT, stdio: "inherit" });
}

// Read current version from obsidian manifest
const manifest = readJson("packages/obsidian/manifest.json");
const currentVersion = manifest.version as string;
console.log(`Current version: ${currentVersion}`);

// Determine new version
const newVersion = process.argv[2] || bumpPatch(currentVersion);
if (!/^\d+\.\d+\.\d+$/.test(newVersion)) {
  console.error(`Invalid version format: ${newVersion} (expected X.Y.Z)`);
  process.exit(1);
}
console.log(`New version: ${newVersion}`);

// Update all version files
for (const file of VERSION_FILES) {
  const data = readJson(file);
  data.version = newVersion;
  writeJson(file, data);
  console.log(`Updated ${file}`);
}

// Update MARKETING_VERSION in desktop project.yml
const projectYmlPath = join(ROOT, DESKTOP_PROJECT_YML);
const projectYml = readFileSync(projectYmlPath, "utf-8");
const updatedYml = projectYml
  .replace(/MARKETING_VERSION: "[^"]+"/, `MARKETING_VERSION: "${newVersion}"`)
  .replace(/CURRENT_PROJECT_VERSION: "\d+"/, (match) => {
    const current = parseInt(match.match(/\d+/)![0]);
    return `CURRENT_PROJECT_VERSION: "${current + 1}"`;
  });
writeFileSync(projectYmlPath, updatedYml);
console.log(`Updated ${DESKTOP_PROJECT_YML}`);

// Update versions.json (add new version mapping)
const versionsData = readJson(VERSIONS_JSON) as Record<string, string>;
const minAppVersion = (readJson("packages/obsidian/manifest.json") as Record<string, string>).minAppVersion;
versionsData[newVersion] = minAppVersion;
writeJson(VERSIONS_JSON, versionsData);
console.log(`Updated ${VERSIONS_JSON}`);

// Commit and tag
run(`git add ${VERSION_FILES.join(" ")} ${VERSIONS_JSON} ${DESKTOP_PROJECT_YML}`);
run(`git commit -m "Bump version to ${newVersion}"`);

// Generate release notes
const prevTag = execSync("git describe --tags --abbrev=0 HEAD~1", { cwd: ROOT }).toString().trim();
const commitLog = execSync(`git log ${prevTag}..HEAD --oneline --no-merges`, { cwd: ROOT }).toString().trim();
console.log(`\nGenerating release notes for ${prevTag}..${newVersion}...`);

let releaseNotes: string;
try {
  execSync("which claude", { cwd: ROOT, stdio: "ignore" });
  const prompt = [
    `Generate concise release notes for version ${newVersion} of the Limn project.`,
    `Here are the commits since ${prevTag}:`,
    "",
    commitLog,
    "",
    "Guidelines:",
    "- Group related commits into a single bullet point",
    "- Focus on user-facing changes, not implementation details",
    "- Skip version bumps, CI changes, and purely internal refactors",
    "- Keep each bullet to one line, use past tense",
    "- Output only a bullet list (- item), nothing else",
  ].join("\n");
  releaseNotes = execSync(`claude -p ${JSON.stringify(prompt)}`, {
    cwd: ROOT, encoding: "utf-8", timeout: 60_000,
  }).trim();
  console.log("Release notes (generated by Claude):");
} catch {
  // claude not available -- fall back to raw commit list
  releaseNotes = commitLog.split("\n")
    .map((line) => `- ${line.replace(/^[0-9a-f]+ /, "")}`)
    .join("\n");
  console.log("Release notes (from commit log):");
}
console.log(releaseNotes);

// Create two annotated tags at the same commit:
//   ${newVersion}            -> triggers the Obsidian plugin release (main.js / manifest.json / styles.css only)
//   desktop-${newVersion}    -> triggers the macOS desktop release (DMG)
// Splitting the tags keeps the Obsidian plugin release free of the DMG, which the
// Obsidian community-plugin scanner flags as an extraneous asset.
const notesFile = join(tmpdir(), `limn-release-notes-${newVersion}.txt`);
writeFileSync(notesFile, releaseNotes);
try {
  run(`git tag -a ${newVersion} -F ${notesFile}`);
  run(`git tag -a desktop-${newVersion} -F ${notesFile}`);
} finally {
  unlinkSync(notesFile);
}

run("git push && git push --tags");

console.log(`\nVersion ${newVersion} released!`);
